name: CI

on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  

# ==================== GATE 1 : Secret Scanning ====================

  git-leaks:
    name: Secret Scanning - GitLeaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    